/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:16:36 GMT 2021
 */

package kz.greetgo.file_storage.impl;

import org.junit.Test;
import static org.junit.Assert.*;
import kz.greetgo.file_storage.impl.Base64Util;

public class Base64UtilTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = Base64Util.base64ToBytes("2o");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = Base64Util.base64ToBytes((String) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = Base64Util.base64ToBytes("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = Base64Util.base64ToBytes("Lp?c8bs");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Base64Util base64Util0 = new Base64Util();
  }
}
