/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:16:36 GMT 2021
 */

package com.pengrad.telegrambot.passport.decrypt;

import org.junit.Test;
import static org.junit.Assert.*;
import com.pengrad.telegrambot.passport.decrypt.Decrypt;

public class DecryptTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Decrypt decrypt0 = new Decrypt();
  }
}
