/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 30 15:25:25 GMT 2021
 */

package edu.mines.jtk.sgl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.mines.jtk.sgl.ArrayStack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class ArrayStack_0_Test {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "edu.mines.jtk.sgl.ArrayStack"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("user.dir", "/usr/src/mymaven/6ce338e3-3c3c-4f52-b595-9b3ed5bb4025"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ArrayStack_0_Test.class.getClassLoader() ,
      "edu.mines.jtk.sgl.ArrayStack"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ArrayStack_0_Test.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "edu.mines.jtk.sgl.ArrayStack"
    );
  }

  //Test case number: 0
  /*
   * 19 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:size()I
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:NonNull
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.size()I:Positive
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.size()I: Line 44
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.size()I
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.size()I
   */

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      arrayStack0.push("D3l0Kiwm{KV(pe");
      int int0 = arrayStack0.size();
      assertEquals(1, int0);
  }

  //Test case number: 1
  /*
   * 23 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:pop()Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:Null
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: Line 32
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 0: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceConstant - 1 -> 0
   * Goal 21. Weak Mutation 1: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> +
   * Goal 22. Weak Mutation 3: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> *
   * Goal 23. Weak Mutation 4: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ArrayStack<String> arrayStack0 = new ArrayStack<String>();
      arrayStack0.push((String) null);
      String string0 = arrayStack0.pop();
      assertNull(string0);
  }

  //Test case number: 2
  /*
   * 23 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:pop()Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:NonNull
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:NonNull
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: Line 32
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 0: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceConstant - 1 -> 0
   * Goal 21. Weak Mutation 1: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> +
   * Goal 22. Weak Mutation 3: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> *
   * Goal 23. Weak Mutation 4: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      Object object0 = new Object();
      Object object1 = arrayStack0.push(object0);
      Object object2 = arrayStack0.pop();
      assertSame(object2, object1);
  }

  //Test case number: 3
  /*
   * 23 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:peek()Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:Null
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: Line 36
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 5: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceConstant - 1 -> 0
   * Goal 21. Weak Mutation 6: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> +
   * Goal 22. Weak Mutation 8: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> *
   * Goal 23. Weak Mutation 9: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      arrayStack0.push((Object) null);
      Object object0 = arrayStack0.peek();
      assertNull(object0);
  }

  //Test case number: 4
  /*
   * 23 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:peek()Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:NonNull
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:NonNull
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: Line 36
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 5: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceConstant - 1 -> 0
   * Goal 21. Weak Mutation 6: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> +
   * Goal 22. Weak Mutation 8: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> *
   * Goal 23. Weak Mutation 9: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArrayStack<String> arrayStack0 = new ArrayStack<String>();
      arrayStack0.push("");
      String string0 = arrayStack0.peek();
      assertEquals("", string0);
  }

  //Test case number: 5
  /*
   * 22 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:get(I)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:NonNull
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:NonNull
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: Line 40
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 10: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp Negation of index
   * Goal 21. Weak Mutation 11: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC 1 index
   * Goal 22. Weak Mutation 12: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC -1 index
   */

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      arrayStack0.push("D3l0Kiwm{KV(pe");
      Object object0 = arrayStack0.get(0);
      assertEquals("D3l0Kiwm{KV(pe", object0);
  }

  //Test case number: 6
  /*
   * 14 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 3. Branch edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:get(I)Ljava/lang/Object;
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 5. get(I)Ljava/lang/Object;_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 6. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 7. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 8. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: Line 40
   * Goal 9. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 10. [METHOD] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 11. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 12. Weak Mutation 10: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp Negation of index
   * Goal 13. Weak Mutation 11: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC 1 index
   * Goal 14. Weak Mutation 12: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC -1 index
   */

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      // Undeclared exception!
      try { 
        arrayStack0.get((-2738));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 7
  /*
   * 12 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch
   * Goal 3. Branch edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:size()I
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 5. [Output]: edu.mines.jtk.sgl.ArrayStack.size()I:Zero
   * Goal 6. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 7. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 8. edu.mines.jtk.sgl.ArrayStack.size()I: Line 44
   * Goal 9. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 10. [METHOD] edu.mines.jtk.sgl.ArrayStack.size()I
   * Goal 11. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 12. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.size()I
   */

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      int int0 = arrayStack0.size();
      assertEquals(0, int0);
  }

  //Test case number: 8
  /*
   * 22 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:get(I)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:Null
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: Line 40
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 20. Weak Mutation 10: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp Negation of index
   * Goal 21. Weak Mutation 11: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC 1 index
   * Goal 22. Weak Mutation 12: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC -1 index
   */

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ArrayStack<String> arrayStack0 = new ArrayStack<String>();
      arrayStack0.push((String) null);
      String string0 = arrayStack0.get(0);
      assertNull(string0);
  }

  //Test case number: 9
  /*
   * 16 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch
   * Goal 3. Branch edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:peek()Ljava/lang/Object;
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 5. peek()Ljava/lang/Object;_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 6. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 7. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 8. edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;: Line 36
   * Goal 9. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 10. [METHOD] edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;
   * Goal 11. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 12. Weak Mutation 5: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceConstant - 1 -> 0
   * Goal 13. Weak Mutation 6: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> +
   * Goal 14. Weak Mutation 7: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> %
   * Goal 15. Weak Mutation 8: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> *
   * Goal 16. Weak Mutation 9: edu.mines.jtk.sgl.ArrayStack.peek()Ljava/lang/Object;:36 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      // Undeclared exception!
      try { 
        arrayStack0.peek();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 10
  /*
   * 16 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch
   * Goal 3. Branch edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:pop()Ljava/lang/Object;
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 5. pop()Ljava/lang/Object;_java.lang.ArrayIndexOutOfBoundsException_IMPLICIT
   * Goal 6. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 7. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 8. edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;: Line 32
   * Goal 9. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 10. [METHOD] edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;
   * Goal 11. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 12. Weak Mutation 0: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceConstant - 1 -> 0
   * Goal 13. Weak Mutation 1: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> +
   * Goal 14. Weak Mutation 2: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> %
   * Goal 15. Weak Mutation 3: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> *
   * Goal 16. Weak Mutation 4: edu.mines.jtk.sgl.ArrayStack.pop()Ljava/lang/Object;:32 - ReplaceArithmeticOperator - -> /
   */

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ArrayStack<String> arrayStack0 = new ArrayStack<String>();
      // Undeclared exception!
      try { 
        arrayStack0.pop();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  //Test case number: 11
  /*
   * 14 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 3. Branch edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:get(I)Ljava/lang/Object;
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 5. get(I)Ljava/lang/Object;_java.lang.IndexOutOfBoundsException_IMPLICIT
   * Goal 6. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 7. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 8. edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;: Line 40
   * Goal 9. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 10. [METHOD] edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;
   * Goal 11. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 12. Weak Mutation 10: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp Negation of index
   * Goal 13. Weak Mutation 11: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC 1 index
   * Goal 14. Weak Mutation 12: edu.mines.jtk.sgl.ArrayStack.get(I)Ljava/lang/Object;:40 - InsertUnaryOp IINC -1 index
   */

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ArrayStack<String> arrayStack0 = new ArrayStack<String>();
      // Undeclared exception!
      try { 
        arrayStack0.get(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }
}
