/*
 * This file was automatically generated by EvoSuite
 * Fri May 09 16:42:12 GMT 2025
 */
package llama31latest;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.Stack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class Stack_0_Test {

    @org.junit.Rule
    public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

    private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone();

    private org.evosuite.runtime.thread.ThreadStopper threadStopper = new org.evosuite.runtime.thread.ThreadStopper(org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);

    @BeforeClass
    public static void initEvoSuiteFramework() {
        org.evosuite.runtime.RuntimeSettings.className = "llama31latest.Stack";
        org.evosuite.runtime.GuiSupport.initialize();
        org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100;
        org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000;
        org.evosuite.runtime.RuntimeSettings.mockSystemIn = true;
        org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED;
        org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT();
        org.evosuite.runtime.classhandling.JDKClassResetter.init();
        setSystemProperties();
        initializeClasses();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
    }

    @AfterClass
    public static void clearEvoSuiteFramework() {
        Sandbox.resetDefaultSecurityManager();
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
    }

    @Before
    public void initTestCase() {
        threadStopper.storeCurrentThreads();
        threadStopper.startRecordingTime();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler();
        org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode();
        setSystemProperties();
        org.evosuite.runtime.GuiSupport.setHeadless();
        org.evosuite.runtime.Runtime.getInstance().resetRuntime();
        org.evosuite.runtime.agent.InstrumentingAgent.activate();
    }

    @After
    public void doneWithTestCase() {
        threadStopper.killAndJoinClientThreads();
        org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks();
        org.evosuite.runtime.classhandling.JDKClassResetter.reset();
        resetClasses();
        org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode();
        org.evosuite.runtime.agent.InstrumentingAgent.deactivate();
        org.evosuite.runtime.GuiSupport.restoreHeadlessMode();
    }

    public static void setSystemProperties() {
        java.lang.System.setProperties((java.util.Properties) defaultProperties.clone());
        java.lang.System.setProperty("user.dir", "/usr/src/mymaven/4bf42102-b5f0-47d7-9c41-4ac084cec277");
        java.lang.System.setProperty("java.io.tmpdir", "/tmp");
    }

    private static void initializeClasses() {
        org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(Stack_0_Test.class.getClassLoader(), "llama31latest.Stack");
    }

    private static void resetClasses() {
        org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(Stack_0_Test.class.getClassLoader());
        org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses("llama31latest.Stack");
    }

    //Test case number: 0
    /*
     * 62 covered goals:
     * Goal 1. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
     * Goal 2. llama31latest.Stack.<init>()V: root-Branch
     * Goal 3. llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - true
     * Goal 4. Branch llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: llama31latest.Stack:push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 5. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 6. Branch llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - true in context: llama31latest.Stack:peek()Ljava/lang/Object;
     * Goal 7. [Output]: llama31latest.Stack.peek()Ljava/lang/Object;:NonNull
     * Goal 8. [Output]: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
     * Goal 9. llama31latest.Stack.<init>()V: Line 9
     * Goal 10. llama31latest.Stack.<init>()V: Line 10
     * Goal 11. llama31latest.Stack.<init>()V: Line 11
     * Goal 12. llama31latest.Stack.<init>()V: Line 12
     * Goal 13. llama31latest.Stack.peek()Ljava/lang/Object;: Line 36
     * Goal 14. llama31latest.Stack.peek()Ljava/lang/Object;: Line 39
     * Goal 15. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 15
     * Goal 16. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 16
     * Goal 17. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 17
     * Goal 18. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 18
     * Goal 19. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 19
     * Goal 20. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 20
     * Goal 21. [METHOD] llama31latest.Stack.<init>()V
     * Goal 22. [METHOD] llama31latest.Stack.peek()Ljava/lang/Object;
     * Goal 23. [METHOD] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 24. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 25. [METHODNOEX] llama31latest.Stack.peek()Ljava/lang/Object;
     * Goal 26. [METHODNOEX] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 27. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 28. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 29. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 30. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 31. Weak Mutation 4: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceConstant - 1 -> 0
     * Goal 32. Weak Mutation 5: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> %
     * Goal 33. Weak Mutation 6: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> -
     * Goal 34. Weak Mutation 7: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> *
     * Goal 35. Weak Mutation 8: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> /
     * Goal 36. Weak Mutation 9: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 37. Weak Mutation 10: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 38. Weak Mutation 11: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceConstant - 1 -> 0
     * Goal 39. Weak Mutation 12: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> +
     * Goal 40. Weak Mutation 13: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> %
     * Goal 41. Weak Mutation 14: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> *
     * Goal 42. Weak Mutation 15: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> /
     * Goal 43. Weak Mutation 16: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp Negation
     * Goal 44. Weak Mutation 17: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp +1
     * Goal 45. Weak Mutation 18: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp -1
     * Goal 46. Weak Mutation 19: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceConstant - 1 -> 0
     * Goal 47. Weak Mutation 20: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> %
     * Goal 48. Weak Mutation 21: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> -
     * Goal 49. Weak Mutation 22: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> *
     * Goal 50. Weak Mutation 23: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> /
     * Goal 51. Weak Mutation 54: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp Negation
     * Goal 52. Weak Mutation 55: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp +1
     * Goal 53. Weak Mutation 56: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp -1
     * Goal 54. Weak Mutation 57: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 0
     * Goal 55. Weak Mutation 58: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 1
     * Goal 56. Weak Mutation 59: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> -2
     * Goal 57. Weak Mutation 61: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> <
     * Goal 58. Weak Mutation 64: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceConstant - 1 -> 0
     * Goal 59. Weak Mutation 65: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> +
     * Goal 60. Weak Mutation 66: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> %
     * Goal 61. Weak Mutation 67: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> *
     * Goal 62. Weak Mutation 68: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> /
     */
    @Test(timeout = 4000)
    public void test0() throws Throwable {
        Stack stack0 = new Stack();
        Object object0 = new Object();
        stack0.push(object0);
        stack0.push(object0);
        stack0.peek();
        assertEquals(2, stack0.size());
    }

    //Test case number: 1
    /*
     * 80 covered goals:
     * Goal 1. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
     * Goal 2. llama31latest.Stack.<init>()V: root-Branch
     * Goal 3. llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - true
     * Goal 4. Branch llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: llama31latest.Stack:push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 5. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 6. Branch llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - true in context: llama31latest.Stack:pop()Ljava/lang/Object;
     * Goal 7. [Output]: llama31latest.Stack.pop()Ljava/lang/Object;:Null
     * Goal 8. [Output]: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
     * Goal 9. llama31latest.Stack.<init>()V: Line 9
     * Goal 10. llama31latest.Stack.<init>()V: Line 10
     * Goal 11. llama31latest.Stack.<init>()V: Line 11
     * Goal 12. llama31latest.Stack.<init>()V: Line 12
     * Goal 13. llama31latest.Stack.pop()Ljava/lang/Object;: Line 24
     * Goal 14. llama31latest.Stack.pop()Ljava/lang/Object;: Line 27
     * Goal 15. llama31latest.Stack.pop()Ljava/lang/Object;: Line 28
     * Goal 16. llama31latest.Stack.pop()Ljava/lang/Object;: Line 29
     * Goal 17. llama31latest.Stack.pop()Ljava/lang/Object;: Line 30
     * Goal 18. llama31latest.Stack.pop()Ljava/lang/Object;: Line 32
     * Goal 19. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 15
     * Goal 20. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 16
     * Goal 21. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 17
     * Goal 22. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 18
     * Goal 23. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 19
     * Goal 24. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 20
     * Goal 25. [METHOD] llama31latest.Stack.<init>()V
     * Goal 26. [METHOD] llama31latest.Stack.pop()Ljava/lang/Object;
     * Goal 27. [METHOD] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 28. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 29. [METHODNOEX] llama31latest.Stack.pop()Ljava/lang/Object;
     * Goal 30. [METHODNOEX] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 31. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 32. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 33. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 34. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 35. Weak Mutation 4: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceConstant - 1 -> 0
     * Goal 36. Weak Mutation 5: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> %
     * Goal 37. Weak Mutation 6: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> -
     * Goal 38. Weak Mutation 7: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> *
     * Goal 39. Weak Mutation 8: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> /
     * Goal 40. Weak Mutation 9: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 41. Weak Mutation 10: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 42. Weak Mutation 11: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceConstant - 1 -> 0
     * Goal 43. Weak Mutation 12: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> +
     * Goal 44. Weak Mutation 13: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> %
     * Goal 45. Weak Mutation 14: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> *
     * Goal 46. Weak Mutation 15: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> /
     * Goal 47. Weak Mutation 16: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp Negation
     * Goal 48. Weak Mutation 17: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp +1
     * Goal 49. Weak Mutation 18: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp -1
     * Goal 50. Weak Mutation 19: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceConstant - 1 -> 0
     * Goal 51. Weak Mutation 20: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> %
     * Goal 52. Weak Mutation 21: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> -
     * Goal 53. Weak Mutation 22: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> *
     * Goal 54. Weak Mutation 23: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> /
     * Goal 55. Weak Mutation 24: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp Negation
     * Goal 56. Weak Mutation 25: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp +1
     * Goal 57. Weak Mutation 26: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp -1
     * Goal 58. Weak Mutation 27: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 0
     * Goal 59. Weak Mutation 28: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 1
     * Goal 60. Weak Mutation 29: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> -2
     * Goal 61. Weak Mutation 31: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceComparisonOperator != -> <
     * Goal 62. Weak Mutation 34: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceConstant - 1 -> 0
     * Goal 63. Weak Mutation 35: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> +
     * Goal 64. Weak Mutation 36: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> %
     * Goal 65. Weak Mutation 37: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> *
     * Goal 66. Weak Mutation 38: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> /
     * Goal 67. Weak Mutation 39: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 0 -> 1
     * Goal 68. Weak Mutation 40: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 0 -> 1
     * Goal 69. Weak Mutation 41: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 1 -> 0
     * Goal 70. Weak Mutation 42: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> +
     * Goal 71. Weak Mutation 43: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> %
     * Goal 72. Weak Mutation 44: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> *
     * Goal 73. Weak Mutation 45: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> /
     * Goal 74. Weak Mutation 46: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp Negation
     * Goal 75. Weak Mutation 47: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp +1
     * Goal 76. Weak Mutation 48: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp -1
     * Goal 77. Weak Mutation 49: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceConstant - 1 -> 0
     * Goal 78. Weak Mutation 50: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> +
     * Goal 79. Weak Mutation 52: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> *
     * Goal 80. Weak Mutation 53: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> /
     */
    @Test(timeout = 4000)
    public void test1() throws Throwable {
        Stack stack0 = new Stack();
        Object object0 = new Object();
        stack0.push(object0);
        stack0.push(object0);
        stack0.pop();
        assertEquals(1, stack0.size());
    }

    //Test case number: 2
    /*
     * 55 covered goals:
     * Goal 1. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
     * Goal 2. llama31latest.Stack.size()I: root-Branch
     * Goal 3. llama31latest.Stack.<init>()V: root-Branch
     * Goal 4. Branch llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: llama31latest.Stack:push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 5. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 6. Branch llama31latest.Stack.size()I: root-Branch in context: llama31latest.Stack:size()I
     * Goal 7. [Output]: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
     * Goal 8. [Output]: llama31latest.Stack.size()I:Positive
     * Goal 9. llama31latest.Stack.<init>()V: Line 9
     * Goal 10. llama31latest.Stack.<init>()V: Line 10
     * Goal 11. llama31latest.Stack.<init>()V: Line 11
     * Goal 12. llama31latest.Stack.<init>()V: Line 12
     * Goal 13. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 15
     * Goal 14. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 16
     * Goal 15. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 17
     * Goal 16. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 18
     * Goal 17. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 19
     * Goal 18. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 20
     * Goal 19. llama31latest.Stack.size()I: Line 43
     * Goal 20. [METHOD] llama31latest.Stack.<init>()V
     * Goal 21. [METHOD] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 22. [METHOD] llama31latest.Stack.size()I
     * Goal 23. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 24. [METHODNOEX] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 25. [METHODNOEX] llama31latest.Stack.size()I
     * Goal 26. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 27. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 28. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 29. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 30. Weak Mutation 4: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceConstant - 1 -> 0
     * Goal 31. Weak Mutation 5: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> %
     * Goal 32. Weak Mutation 6: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> -
     * Goal 33. Weak Mutation 7: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> *
     * Goal 34. Weak Mutation 8: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> /
     * Goal 35. Weak Mutation 9: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 36. Weak Mutation 10: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 37. Weak Mutation 11: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceConstant - 1 -> 0
     * Goal 38. Weak Mutation 12: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> +
     * Goal 39. Weak Mutation 14: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> *
     * Goal 40. Weak Mutation 15: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> /
     * Goal 41. Weak Mutation 16: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp Negation
     * Goal 42. Weak Mutation 17: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp +1
     * Goal 43. Weak Mutation 18: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp -1
     * Goal 44. Weak Mutation 19: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceConstant - 1 -> 0
     * Goal 45. Weak Mutation 21: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> -
     * Goal 46. Weak Mutation 22: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> *
     * Goal 47. Weak Mutation 23: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> /
     * Goal 48. Weak Mutation 69: llama31latest.Stack.size()I:43 - InsertUnaryOp Negation
     * Goal 49. Weak Mutation 70: llama31latest.Stack.size()I:43 - InsertUnaryOp +1
     * Goal 50. Weak Mutation 71: llama31latest.Stack.size()I:43 - InsertUnaryOp -1
     * Goal 51. Weak Mutation 72: llama31latest.Stack.size()I:43 - ReplaceConstant - 1 -> 0
     * Goal 52. Weak Mutation 73: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> %
     * Goal 53. Weak Mutation 74: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> -
     * Goal 54. Weak Mutation 75: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> *
     * Goal 55. Weak Mutation 76: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> /
     */
    @Test(timeout = 4000)
    public void test2() throws Throwable {
        Stack stack0 = new Stack();
        Object object0 = new Object();
        stack0.push(object0);
        int int0 = stack0.size();
        assertEquals(1, int0);
    }

    //Test case number: 3
    /*
     * 59 covered goals:
     * Goal 1. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
     * Goal 2. llama31latest.Stack.<init>()V: root-Branch
     * Goal 3. llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - true
     * Goal 4. Branch llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: llama31latest.Stack:push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 5. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 6. Branch llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - true in context: llama31latest.Stack:peek()Ljava/lang/Object;
     * Goal 7. [Output]: llama31latest.Stack.peek()Ljava/lang/Object;:Null
     * Goal 8. [Output]: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
     * Goal 9. llama31latest.Stack.<init>()V: Line 9
     * Goal 10. llama31latest.Stack.<init>()V: Line 10
     * Goal 11. llama31latest.Stack.<init>()V: Line 11
     * Goal 12. llama31latest.Stack.<init>()V: Line 12
     * Goal 13. llama31latest.Stack.peek()Ljava/lang/Object;: Line 36
     * Goal 14. llama31latest.Stack.peek()Ljava/lang/Object;: Line 39
     * Goal 15. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 15
     * Goal 16. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 16
     * Goal 17. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 17
     * Goal 18. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 18
     * Goal 19. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 19
     * Goal 20. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 20
     * Goal 21. [METHOD] llama31latest.Stack.<init>()V
     * Goal 22. [METHOD] llama31latest.Stack.peek()Ljava/lang/Object;
     * Goal 23. [METHOD] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 24. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 25. [METHODNOEX] llama31latest.Stack.peek()Ljava/lang/Object;
     * Goal 26. [METHODNOEX] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 27. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 28. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 29. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 30. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 31. Weak Mutation 4: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceConstant - 1 -> 0
     * Goal 32. Weak Mutation 5: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> %
     * Goal 33. Weak Mutation 6: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> -
     * Goal 34. Weak Mutation 7: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> *
     * Goal 35. Weak Mutation 8: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> /
     * Goal 36. Weak Mutation 9: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 37. Weak Mutation 10: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 38. Weak Mutation 11: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceConstant - 1 -> 0
     * Goal 39. Weak Mutation 12: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> +
     * Goal 40. Weak Mutation 14: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> *
     * Goal 41. Weak Mutation 15: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> /
     * Goal 42. Weak Mutation 16: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp Negation
     * Goal 43. Weak Mutation 17: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp +1
     * Goal 44. Weak Mutation 18: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp -1
     * Goal 45. Weak Mutation 19: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceConstant - 1 -> 0
     * Goal 46. Weak Mutation 21: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> -
     * Goal 47. Weak Mutation 22: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> *
     * Goal 48. Weak Mutation 23: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> /
     * Goal 49. Weak Mutation 54: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp Negation
     * Goal 50. Weak Mutation 55: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp +1
     * Goal 51. Weak Mutation 56: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp -1
     * Goal 52. Weak Mutation 57: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 0
     * Goal 53. Weak Mutation 58: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 1
     * Goal 54. Weak Mutation 59: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> -2
     * Goal 55. Weak Mutation 61: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> <
     * Goal 56. Weak Mutation 64: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceConstant - 1 -> 0
     * Goal 57. Weak Mutation 65: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> +
     * Goal 58. Weak Mutation 67: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> *
     * Goal 59. Weak Mutation 68: llama31latest.Stack.peek()Ljava/lang/Object;:39 - ReplaceArithmeticOperator - -> /
     */
    @Test(timeout = 4000)
    public void test3() throws Throwable {
        Stack stack0 = new Stack();
        stack0.push((Object) null);
        stack0.peek();
        assertEquals(1, stack0.size());
    }

    //Test case number: 4
    /*
     * 26 covered goals:
     * Goal 1. llama31latest.Stack.<init>()V: root-Branch
     * Goal 2. llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - false
     * Goal 3. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 4. Branch llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - false in context: llama31latest.Stack:pop()Ljava/lang/Object;
     * Goal 5. pop()Ljava/lang/Object;_java.lang.RuntimeException_EXPLICIT
     * Goal 6. llama31latest.Stack.<init>()V: Line 9
     * Goal 7. llama31latest.Stack.<init>()V: Line 10
     * Goal 8. llama31latest.Stack.<init>()V: Line 11
     * Goal 9. llama31latest.Stack.<init>()V: Line 12
     * Goal 10. llama31latest.Stack.pop()Ljava/lang/Object;: Line 24
     * Goal 11. llama31latest.Stack.pop()Ljava/lang/Object;: Line 25
     * Goal 12. [METHOD] llama31latest.Stack.<init>()V
     * Goal 13. [METHOD] llama31latest.Stack.pop()Ljava/lang/Object;
     * Goal 14. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 15. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 16. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 17. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 18. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 19. Weak Mutation 24: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp Negation
     * Goal 20. Weak Mutation 25: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp +1
     * Goal 21. Weak Mutation 26: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp -1
     * Goal 22. Weak Mutation 27: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 0
     * Goal 23. Weak Mutation 28: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 1
     * Goal 24. Weak Mutation 29: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> -2
     * Goal 25. Weak Mutation 30: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceComparisonOperator != -> -1
     * Goal 26. Weak Mutation 33: llama31latest.Stack.pop()Ljava/lang/Object;:25 - ReplaceConstant - Stack is empty ->
     */
    @Test(timeout = 4000)
    public void test4() throws Throwable {
        Stack stack0 = new Stack();
        // Undeclared exception!
        try {
            stack0.pop();
            fail("Expecting exception: RuntimeException");
        } catch (RuntimeException e) {
            //
            // Stack is empty
            //
            verifyException("llama31latest.Stack", e);
        }
    }

    //Test case number: 5
    /*
     * 25 covered goals:
     * Goal 1. llama31latest.Stack.size()I: root-Branch
     * Goal 2. llama31latest.Stack.<init>()V: root-Branch
     * Goal 3. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 4. Branch llama31latest.Stack.size()I: root-Branch in context: llama31latest.Stack:size()I
     * Goal 5. [Output]: llama31latest.Stack.size()I:Zero
     * Goal 6. llama31latest.Stack.<init>()V: Line 9
     * Goal 7. llama31latest.Stack.<init>()V: Line 10
     * Goal 8. llama31latest.Stack.<init>()V: Line 11
     * Goal 9. llama31latest.Stack.<init>()V: Line 12
     * Goal 10. llama31latest.Stack.size()I: Line 43
     * Goal 11. [METHOD] llama31latest.Stack.<init>()V
     * Goal 12. [METHOD] llama31latest.Stack.size()I
     * Goal 13. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 14. [METHODNOEX] llama31latest.Stack.size()I
     * Goal 15. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 16. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 17. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 18. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 19. Weak Mutation 69: llama31latest.Stack.size()I:43 - InsertUnaryOp Negation
     * Goal 20. Weak Mutation 70: llama31latest.Stack.size()I:43 - InsertUnaryOp +1
     * Goal 21. Weak Mutation 71: llama31latest.Stack.size()I:43 - InsertUnaryOp -1
     * Goal 22. Weak Mutation 72: llama31latest.Stack.size()I:43 - ReplaceConstant - 1 -> 0
     * Goal 23. Weak Mutation 74: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> -
     * Goal 24. Weak Mutation 75: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> *
     * Goal 25. Weak Mutation 76: llama31latest.Stack.size()I:43 - ReplaceArithmeticOperator + -> /
     */
    @Test(timeout = 4000)
    public void test5() throws Throwable {
        Stack stack0 = new Stack();
        int int0 = stack0.size();
        assertEquals(0, int0);
    }

    //Test case number: 6
    /*
     * 91 covered goals:
     * Goal 1. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
     * Goal 2. llama31latest.Stack.<init>()V: root-Branch
     * Goal 3. llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - true
     * Goal 4. llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - false
     * Goal 5. Branch llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: llama31latest.Stack:push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 6. Branch llama31latest.Stack.<init>()V: root-Branch in context: llama31latest.Stack:<init>()V
     * Goal 7. Branch llama31latest.Stack.pop()Ljava/lang/Object;: I5 Branch 1 IF_ICMPNE L24 - true in context: llama31latest.Stack:pop()Ljava/lang/Object;
     * Goal 8. Branch llama31latest.Stack.peek()Ljava/lang/Object;: I5 Branch 2 IF_ICMPNE L36 - false in context: llama31latest.Stack:peek()Ljava/lang/Object;
     * Goal 9. peek()Ljava/lang/Object;_java.lang.RuntimeException_EXPLICIT
     * Goal 10. [Output]: llama31latest.Stack.pop()Ljava/lang/Object;:Null
     * Goal 11. [Output]: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:Null
     * Goal 12. llama31latest.Stack.<init>()V: Line 9
     * Goal 13. llama31latest.Stack.<init>()V: Line 10
     * Goal 14. llama31latest.Stack.<init>()V: Line 11
     * Goal 15. llama31latest.Stack.<init>()V: Line 12
     * Goal 16. llama31latest.Stack.peek()Ljava/lang/Object;: Line 36
     * Goal 17. llama31latest.Stack.peek()Ljava/lang/Object;: Line 37
     * Goal 18. llama31latest.Stack.pop()Ljava/lang/Object;: Line 24
     * Goal 19. llama31latest.Stack.pop()Ljava/lang/Object;: Line 27
     * Goal 20. llama31latest.Stack.pop()Ljava/lang/Object;: Line 28
     * Goal 21. llama31latest.Stack.pop()Ljava/lang/Object;: Line 29
     * Goal 22. llama31latest.Stack.pop()Ljava/lang/Object;: Line 30
     * Goal 23. llama31latest.Stack.pop()Ljava/lang/Object;: Line 32
     * Goal 24. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 15
     * Goal 25. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 16
     * Goal 26. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 17
     * Goal 27. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 18
     * Goal 28. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 19
     * Goal 29. llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 20
     * Goal 30. [METHOD] llama31latest.Stack.<init>()V
     * Goal 31. [METHOD] llama31latest.Stack.peek()Ljava/lang/Object;
     * Goal 32. [METHOD] llama31latest.Stack.pop()Ljava/lang/Object;
     * Goal 33. [METHOD] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 34. [METHODNOEX] llama31latest.Stack.<init>()V
     * Goal 35. [METHODNOEX] llama31latest.Stack.pop()Ljava/lang/Object;
     * Goal 36. [METHODNOEX] llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;
     * Goal 37. Weak Mutation 0: llama31latest.Stack.<init>()V:10 - ReplaceConstant - 0 -> 1
     * Goal 38. Weak Mutation 1: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 0
     * Goal 39. Weak Mutation 2: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> 1
     * Goal 40. Weak Mutation 3: llama31latest.Stack.<init>()V:11 - ReplaceConstant - -1 -> -2
     * Goal 41. Weak Mutation 4: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceConstant - 1 -> 0
     * Goal 42. Weak Mutation 5: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> %
     * Goal 43. Weak Mutation 6: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> -
     * Goal 44. Weak Mutation 7: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> *
     * Goal 45. Weak Mutation 8: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:15 - ReplaceArithmeticOperator + -> /
     * Goal 46. Weak Mutation 9: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 47. Weak Mutation 10: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:16 - ReplaceConstant - 0 -> 1
     * Goal 48. Weak Mutation 11: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceConstant - 1 -> 0
     * Goal 49. Weak Mutation 12: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> +
     * Goal 50. Weak Mutation 14: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> *
     * Goal 51. Weak Mutation 15: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:17 - ReplaceArithmeticOperator - -> /
     * Goal 52. Weak Mutation 16: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp Negation
     * Goal 53. Weak Mutation 17: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp +1
     * Goal 54. Weak Mutation 18: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - InsertUnaryOp -1
     * Goal 55. Weak Mutation 19: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceConstant - 1 -> 0
     * Goal 56. Weak Mutation 21: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> -
     * Goal 57. Weak Mutation 22: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> *
     * Goal 58. Weak Mutation 23: llama31latest.Stack.push(Ljava/lang/Object;)Ljava/lang/Object;:19 - ReplaceArithmeticOperator + -> /
     * Goal 59. Weak Mutation 24: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp Negation
     * Goal 60. Weak Mutation 25: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp +1
     * Goal 61. Weak Mutation 26: llama31latest.Stack.pop()Ljava/lang/Object;:24 - InsertUnaryOp -1
     * Goal 62. Weak Mutation 27: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 0
     * Goal 63. Weak Mutation 28: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> 1
     * Goal 64. Weak Mutation 29: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceConstant - -1 -> -2
     * Goal 65. Weak Mutation 31: llama31latest.Stack.pop()Ljava/lang/Object;:24 - ReplaceComparisonOperator != -> <
     * Goal 66. Weak Mutation 34: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceConstant - 1 -> 0
     * Goal 67. Weak Mutation 35: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> +
     * Goal 68. Weak Mutation 37: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> *
     * Goal 69. Weak Mutation 38: llama31latest.Stack.pop()Ljava/lang/Object;:27 - ReplaceArithmeticOperator - -> /
     * Goal 70. Weak Mutation 39: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 0 -> 1
     * Goal 71. Weak Mutation 40: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 0 -> 1
     * Goal 72. Weak Mutation 41: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceConstant - 1 -> 0
     * Goal 73. Weak Mutation 42: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> +
     * Goal 74. Weak Mutation 44: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> *
     * Goal 75. Weak Mutation 45: llama31latest.Stack.pop()Ljava/lang/Object;:28 - ReplaceArithmeticOperator - -> /
     * Goal 76. Weak Mutation 46: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp Negation
     * Goal 77. Weak Mutation 47: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp +1
     * Goal 78. Weak Mutation 48: llama31latest.Stack.pop()Ljava/lang/Object;:30 - InsertUnaryOp -1
     * Goal 79. Weak Mutation 49: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceConstant - 1 -> 0
     * Goal 80. Weak Mutation 50: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> +
     * Goal 81. Weak Mutation 51: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> %
     * Goal 82. Weak Mutation 52: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> *
     * Goal 83. Weak Mutation 53: llama31latest.Stack.pop()Ljava/lang/Object;:30 - ReplaceArithmeticOperator - -> /
     * Goal 84. Weak Mutation 54: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp Negation
     * Goal 85. Weak Mutation 55: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp +1
     * Goal 86. Weak Mutation 56: llama31latest.Stack.peek()Ljava/lang/Object;:36 - InsertUnaryOp -1
     * Goal 87. Weak Mutation 57: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 0
     * Goal 88. Weak Mutation 58: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> 1
     * Goal 89. Weak Mutation 59: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceConstant - -1 -> -2
     * Goal 90. Weak Mutation 60: llama31latest.Stack.peek()Ljava/lang/Object;:36 - ReplaceComparisonOperator != -> -1
     * Goal 91. Weak Mutation 63: llama31latest.Stack.peek()Ljava/lang/Object;:37 - ReplaceConstant - Stack is empty ->
     */
    @Test(timeout = 4000)
    public void test6() throws Throwable {
        Stack stack0 = new Stack();
        Object object0 = new Object();
        stack0.push(object0);
        stack0.pop();
        stack0.push((Object) null);
        stack0.pop();
        // Undeclared exception!
        try {
            stack0.peek();
            fail("Expecting exception: RuntimeException");
        } catch (RuntimeException e) {
            //
            // Stack is empty
            //
            verifyException("llama31latest.Stack", e);
        }
    }
}