/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 30 15:25:25 GMT 2021
 */

package edu.mines.jtk.sgl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.mines.jtk.sgl.ArrayStack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

public class ArrayStack_0_Test {

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();
      String str = "blub";
      String object0 = new String(str);
      object0.substring(0,2);
      Object object1 = arrayStack0.push(object0);
      Object object2 = arrayStack0.pop();
      assertSame(object2, object1);
  }
}
