/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 30 15:25:25 GMT 2021
 */

package edu.mines.jtk.sgl;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import edu.mines.jtk.sgl.ArrayStack;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.runner.RunWith;

public class ArrayStack_0_Test {

  //Test case number: 0
  /*
   * 19 covered goals:
   * Goal 1. edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch
   * Goal 2. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch
   * Goal 3. edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch
   * Goal 4. Branch edu.mines.jtk.sgl.ArrayStack.size()I: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:size()I
   * Goal 5. Branch edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: root-Branch in context: edu.mines.jtk.sgl.ArrayStack:push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 6. Branch edu.mines.jtk.sgl.ArrayStack.<init>()V: root-Branch in context: 
   * Goal 7. [Output]: edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;:NonNull
   * Goal 8. [Output]: edu.mines.jtk.sgl.ArrayStack.size()I:Positive
   * Goal 9. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 24
   * Goal 10. edu.mines.jtk.sgl.ArrayStack.<init>()V: Line 47
   * Goal 11. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 27
   * Goal 12. edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;: Line 28
   * Goal 13. edu.mines.jtk.sgl.ArrayStack.size()I: Line 44
   * Goal 14. [METHOD] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 15. [METHOD] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 16. [METHOD] edu.mines.jtk.sgl.ArrayStack.size()I
   * Goal 17. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.<init>()V
   * Goal 18. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.push(Ljava/lang/Object;)Ljava/lang/Object;
   * Goal 19. [METHODNOEX] edu.mines.jtk.sgl.ArrayStack.size()I
   */

  @Test(timeout = 4000)
  public void test00_static_field()  throws Throwable  {
      ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();

      int math = Math.PI;
      arrayStack0.push(math);

      int int0 = arrayStack0.size();
      assertEquals(1, int0);
  }

    @Test(timeout = 4000)
    public void test00_static_method()  throws Throwable  {
        ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();

        int math = Math.abs(-5);
        arrayStack0.push(math);

        java.lang.Math.abs(10);

        int int0 = arrayStack0.size();
        assertEquals(1, int0);
    }

    @Test(timeout = 4000)
    public void test00_array()  throws Throwable  {
        ArrayStack<Object> arrayStack0 = new ArrayStack<Object>();

        String[][] multi = new String[][]{{"hello"}, {"world"}};

        String[] myArr = new String[]{"hello", "world"};
        myArr[1] = "marcus";

        myArr[0] = new String("hi");

        multi[1] = myArr;

        String[] nullinger = null;

        arrayStack0.push(null);

        int int0 = arrayStack0.size();
        assertEquals(1, int0);
    }

}
