/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:14:32 GMT 2021
 */

package org.apache.ws.commons.util;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.IOException;
import org.apache.ws.commons.util.Base64;
import org.xml.sax.SAXException;
import org.xml.sax.ext.DefaultHandler2;

public class Base64Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("PxFV");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64.decode((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("\n");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Base64 base64_0 = new Base64();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Base64.DecodingException base64_DecodingException0 = new Base64.DecodingException("");
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      char[] charArray0 = new char[5];
      DefaultHandler2 defaultHandler2_0 = new DefaultHandler2();
      Base64.SAXEncoder base64_SAXEncoder0 = new Base64.SAXEncoder(charArray0, 0, ")JBi8LSw7+kG1g{. p", defaultHandler2_0);
      Base64.EncoderOutputStream base64_EncoderOutputStream0 = new Base64.EncoderOutputStream(base64_SAXEncoder0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      SAXException sAXException0 = new SAXException();
      Base64.SAXIOException base64_SAXIOException0 = new Base64.SAXIOException(sAXException0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("00X=");
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      try { 
        Base64.decode("Q=l$:Hm");
      } catch(IOException e) {
         //
         // Unexpected end of stream character (=)
         //
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      try { 
        Base64.decode("Invalil value or nuBytes");
      } catch(IOException e) {
         //
         // Unexpected end of file
         //
      }
  }
}
