/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:14:32 GMT 2021
 */

package studio.wetrack.base.utils.encrypt;

import org.junit.Test;
import static org.junit.Assert.*;
import studio.wetrack.base.utils.encrypt.Base64;

public class Base64Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("7P]~sQxwrLPVhX .z_");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = Base64.decode((String) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Base64 base64_0 = new Base64();
  }
}
