/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:14:30 GMT 2021
 */

package net.sourceforge.cardme.util;

import org.junit.Test;
import static org.junit.Assert.*;
import net.sourceforge.cardme.util.Base64Wrapper;

public class Base64WrapperTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64Wrapper.decode("KL");
      } catch(IllegalArgumentException e) {
         //
         // Base64-encoded string must have at least four characters, but length specified was 2
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64Wrapper.decode((String) null);
      } catch(NullPointerException e) {
         //
         // Input string was null.
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64Wrapper.decode("net.sourceforge.cardme.util.Base64Wrapper$1");
      } catch(RuntimeException e) {
         //
         // Bad Base64 input character decimal 46 in array position 3
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = Base64Wrapper.decode("");
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = Base64Wrapper.decode("qiv8M");
  }
}
