/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:16:52 GMT 2021
 */

package com.shuwang.algorithm.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.shuwang.algorithm.util.AlgorithmBase64Util;

public class AlgorithmBase64UtilTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = AlgorithmBase64Util.decodeBASE64(">k@fm@#[I_)y");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      try { 
        AlgorithmBase64Util.decodeBASE64((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = AlgorithmBase64Util.decodeBASE64("");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AlgorithmBase64Util algorithmBase64Util0 = new AlgorithmBase64Util();
  }
}
