/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:16:47 GMT 2021
 */

package com.google.crypto.tink.subtle;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.crypto.tink.subtle.Base64;

public class Base64Test {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64.decode(",;[/Wm+?v!");
      } catch(IllegalArgumentException e) {
         //
         // bad base-64
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        Base64.decode((String) null);
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("4N");
      Base64.Encoder base64_Encoder0 = new Base64.Encoder(110, byteArray0);
      Base64.Encoder base64_Encoder1 = new Base64.Encoder(1, base64_Encoder0.output);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("UTF-8");
      Base64.Decoder base64_Decoder0 = new Base64.Decoder((-3366), byteArray0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("UTF-8");
      Base64.Encoder base64_Encoder0 = new Base64.Encoder(0, byteArray0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("US-ASCII");
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      byte[] byteArray0 = Base64.decode("f5gc{|& ");
  }
}
