/*
 * LASSO - an Observatorium for the Dynamic Selection, Analysis and Comparison of Software
 * Copyright (C) 2024 Marcus Kessel (University of Mannheim) and LASSO contributers
 *
 * This file is part of LASSO.
 *
 * LASSO is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * LASSO is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with LASSO.  If not, see <https://www.gnu.org/licenses/>.
 */
/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:19:05 GMT 2021
 */

package oracle.kv.shell;

import org.junit.Test;
import static org.junit.Assert.*;
import oracle.kv.shell.CommandUtils;

public class CommandUtilsTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      try { 
        CommandUtils.decodeBase64("59`vn#");
      } catch(Exception e) {
         //
         // Get Exception in Base64 decoding:org.evosuite.runtime.mock.java.lang.MockThrowable: Illegal character '`' (code 0x60) in base64 content
         //  at [Source: java.lang.String@0000000018; line: -1, column: -1]
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64("zoJsF");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64((String) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CommandUtils commandUtils0 = new CommandUtils();
  }
}
