/*
 * This file was automatically generated by EvoSuite
 * Tue Mar 02 18:19:05 GMT 2021
 */

package oracle.kv.shell;

import org.junit.Test;
import static org.junit.Assert.*;
import oracle.kv.shell.CommandUtils;

public class CommandUtilsTest {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      try { 
        CommandUtils.decodeBase64("59`vn#");
      } catch(Exception e) {
         //
         // Get Exception in Base64 decoding:org.evosuite.runtime.mock.java.lang.MockThrowable: Illegal character '`' (code 0x60) in base64 content
         //  at [Source: java.lang.String@0000000018; line: -1, column: -1]
         //
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64("");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64("zoJsF");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = CommandUtils.decodeBase64((String) null);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CommandUtils commandUtils0 = new CommandUtils();
  }
}
